import os
import smtplib
from email.message import EmailMessage

SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587

SMTP_USERNAME = "imageintel.demo@gmail.com"
SMTP_PASSWORD = "uxgy woit ixhg bcem"

MAIL_FROM = "imageintel.demo@gmail.com"


def send_pdf_email(recipient_email, pdf_path):

    if not os.path.exists(pdf_path):
        raise FileNotFoundError("PDF file not found")

    msg = EmailMessage()
    msg["Subject"] = "Image Intel – Your OSINT Analysis Report"
    msg["From"] = f"Image Intel <{MAIL_FROM}>"
    msg["To"] = recipient_email
    msg["Reply-To"] = MAIL_FROM
    msg["X-Mailer"] = "Image Intel Analyzer"
    msg["Precedence"] = "bulk"

    msg.set_content(
        """Hello,
    
        Your Image Intel analysis report is attached.
    
        This report contains:
        • EXIF metadata analysis
        • GPS map extraction
        • Timeline reconstruction
        • Automated insights
    
        Generated automatically by Image Intel.
    
        Best regards,
        Image Intel
        """
    )
    msg.add_alternative("""
    <html>
    <body>
    <h2>Image Intel Report</h2>

    <p>Your analysis report is attached.</p>

    <p>This report includes:</p>
    <ul>
    <li>EXIF metadata extraction</li>
    <li>GPS location analysis</li>
    <li>Timeline reconstruction</li>
    <li>Automated insights</li>
    </ul>

    <p>Generated by <b>Image Intel</b>.</p>

    </body>
    </html>
    """, subtype="html")

    with open(pdf_path, "rb") as f:
        pdf_data = f.read()

    msg.add_attachment(
        pdf_data,
        maintype="application",
        subtype="pdf",
        filename="image_intel_report.pdf"
    )

    with smtplib.SMTP(SMTP_SERVER, SMTP_PORT) as server:
        server.starttls()
        server.login(SMTP_USERNAME, SMTP_PASSWORD)
        server.send_message(msg)